version: '3.8'

services:
  frontend:
    container_name: simple_web_stack_frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # Add volumes for development for live-reloading
    volumes:
      - ./frontend:/app
    # Override the default command to run the development server
    command: ["deno", "task", "dev"]

  backend:
    container_name: simple_web_stack_backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    # Optional: Add volumes for development if needed, though less common for compiled Rust
    # volumes:
    #   - ./backend:/usr/src/app 
    #   Note: Ensure paths align with your Dockerfile WORKDIR and build process 