name: Backend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'backend/**'
      - '.github/workflows/backend-ci.yml' # Also run if the workflow itself changes

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test_backend:
    name: Build and Test Backend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          components: rustfmt, clippy
          cache-workspaces: ./backend

      - name: Check formatting (Rustfmt)
        run: cargo fmt --all -- --check

      - name: Lint with Clippy
        run: cargo clippy -- -D warnings # Fail on warnings

      - name: Build backend
        run: cargo build --verbose # No --release for CI as per your rules

      - name: Run tests
        run: cargo test --verbose # Runs tests defined in the Rust project