name: Backend CI

on:
  push:
    branches:
      - main # or your default branch
  pull_request:
    paths:
      - 'backend/**'

jobs:
  build_backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo dependencies
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: "./backend -> target"

      - name: Build project
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose