name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend-ci.yml' # Also run if the workflow itself changes

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build_and_test_frontend:
    name: Build and Test Frontend
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/deno # Default Deno cache directory on Linux for 'ubuntu-latest'
          key: ${{ runner.os }}-deno-${{ hashFiles('frontend/deno.json', 'frontend/deno.lock') }}
          restore-keys: |
            ${{ runner.os }}-deno-

      - name: Install frontend dependencies (if explicit step is needed, e.g. deno cache main.ts)
        run: deno cache main.ts # This ensures dependencies in main.ts and its imports are fetched

      - name: Check formatting, lint, and types
        run: deno task check # Uses the 'check' task from frontend/deno.json

      # If you have a specific build command for CI validation (Fresh often relies on JIT for dev)
      # - name: Build frontend
      #   run: deno task build

      # If you have a specific test command (deno task check already includes type checking)
      - name: Run tests
        run: deno task test