name: Frontend CI (simple-web-stack context)

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**' # Relative to simple-web-stack root
  pull_request:
    paths:
      - 'frontend/**' # Relative to simple-web-stack root

jobs:
  build_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend # Relative to simple-web-stack root
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # This will checkout the simple-web-stack repository.
        # The working-directory then scopes commands to simple-web-stack/frontend/

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x # Use Deno v2.x which supports lockfile version 5

      - name: Check code (format, lint, type check)
        run: deno task check

      - name: Build project
        run: deno task build